@startuml

skinparam maxactorsize 0

skinparam rectangle {
    BackgroundColor white
    BorderColor white
    shadowing false
}

usecase "Input\nImage" as input

agent "Property<FONT POINT-SIZE='10'><SUB>1</SUB></FONT>\nTransform<FONT POINT-SIZE='10'><SUB>1</SUB></FONT>" as TRANS_1
agent "Property<FONT POINT-SIZE='10'><SUB>1</SUB></FONT>\nTransform<FONT POINT-SIZE='10'><SUB>2</SUB></FONT>" as TRANS_11
agent "Property<FONT POINT-SIZE='10'><SUB>2</SUB></FONT>\nTransform<FONT POINT-SIZE='10'><SUB>1</SUB></FONT>" as TRANS_2
agent "Property<FONT POINT-SIZE='10'><SUB>3</SUB></FONT>\nTransform<FONT POINT-SIZE='10'><SUB>1</SUB></FONT>" as TRANS_3
agent "Property<FONT POINT-SIZE='10'><SUB>n</SUB></FONT>\nTransform<FONT POINT-SIZE='10'><SUB>m</SUB></FONT>" as TRANS_N

input --> TRANS_1
input --> TRANS_11
input --> TRANS_2
input --> TRANS_3
input --> TRANS_N

agent "Property<FONT POINT-SIZE='10'><SUB>1</SUB></FONT>\nTransform<FONT POINT-SIZE='10'><SUB>1</SUB></FONT>\nNeural Net" as XAI_1
agent "Property<FONT POINT-SIZE='10'><SUB>1</SUB></FONT>\nTransform<FONT POINT-SIZE='10'><SUB>2</SUB></FONT>\nNeural Net" as XAI_11
agent "Property<FONT POINT-SIZE='10'><SUB>2</SUB></FONT>\nTransform<FONT POINT-SIZE='10'><SUB>1</SUB></FONT>\nNeural Net" as XAI_2
agent "Property<FONT POINT-SIZE='10'><SUB>3</SUB></FONT>\nTransform<FONT POINT-SIZE='10'><SUB>1</SUB></FONT>\nNeural Net" as XAI_3
agent "Property<FONT POINT-SIZE='10'><SUB>n</SUB></FONT>\nTransform<FONT POINT-SIZE='10'><SUB>m</SUB></FONT>\nNeural Net" as XAI_N

TRANS_1 --> XAI_1
TRANS_11 --> XAI_11
TRANS_2 --> XAI_2
TRANS_3 --> XAI_3
TRANS_N --> XAI_N

XAI_1 .[hidden]right. XAI_11
XAI_11 .[hidden]right. XAI_2
XAI_2 .[hidden]right. XAI_3
XAI_3 .right. XAI_N

package "Explainability" as exp {
usecase "Property<FONT POINT-SIZE='10'><SUB>1</SUB></FONT>\nTransform<FONT POINT-SIZE='10'><SUB>1</SUB></FONT>\nClassification" as label_1

usecase "Property<FONT POINT-SIZE='10'><SUB>1</SUB></FONT>\nTransform<FONT POINT-SIZE='10'><SUB>2</SUB></FONT>\nClassification" as label_11

usecase "Property<FONT POINT-SIZE='10'><SUB>2</SUB></FONT>\nTransform<FONT POINT-SIZE='10'><SUB>1</SUB></FONT>\nClassification" as label_2

usecase "Property<FONT POINT-SIZE='10'><SUB>3</SUB></FONT>\nTransform<FONT POINT-SIZE='10'><SUB>1</SUB></FONT>\nClassification" as label_3

usecase "Property<FONT POINT-SIZE='10'><SUB>n</SUB></FONT>\nTransform<FONT POINT-SIZE='10'><SUB>m</SUB></FONT>\nClassification" as label_N
}

XAI_1 --> label_1
XAI_11 --> label_11
XAI_2 --> label_2
XAI_3 --> label_3
XAI_N --> label_N

agent "Classification\nScheme" as cls_sch

label_1 --> cls_sch
label_11 --> cls_sch
label_2 --> cls_sch
label_3 --> cls_sch
label_N --> cls_sch

usecase "Final\nClassification" as final

cls_sch --> final

usecase "Explanation" as explain

exp -down-> explain

final -[hidden]right-- explain

@enduml
